dependencies:
  - role: kernel
    tags:
      - kernel
  - role: qemu
    tags:
      - qemu
  - role: radamsa
    tags:
      - radamsa
  - role: ghidra
    tags:
      - ghidra
  # optional targets dependency
  - role: targets
    tags:
      - targets
