dependencies:
  - role: kernel
    tags:
      - kernel
  - role: qemu
    tags:
      - qemu
  - role: radamsa
    tags:
      - radamsa
  - role: ghidra
    tags:
      - ghidra
  - role: examples
    tags:
      - examples
