- hosts: all
  environment:
    http_proxy: "{{ proxy_env.http_proxy | default(lookup('env', 'http_proxy')) }}"
    https_proxy: "{{ proxy_env.https_proxy | default(lookup('env', 'https_proxy')) }}"
  pre_tasks:
    - name: apt update to ensure root access is available (or fail early)
      apt:
        update_cache: true
      become: true

  roles:
    - role: intellabs.kafl.fuzzer
      tags:
        - fuzzer
      vars:
        # branches maintained for this version
        - fuzzer_revision:      'v0.5.1'
        - qemu_revision:        'kafl-v0.5'
        - examples_revision:    'v0.1'
        # no maintained branch - try latest
        #- libxdc_revision:     'ec596317'
        #- capstone_revision:   '0efa3cc5'
        #- radamsa_revision:    'df651a67'
        #- nyx_packer_revision: 'ef990c60'
